# Generated by Django 5.2.7 on 2025-10-14 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='eventos.evento')),
                ('usuario_afectado', models.ForeignKey(blank=True, help_text='Usuario sobre el que se realizó la acción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_ejecutor', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_ejecutados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Evento',
                'verbose_name_plural': 'Registros de Eventos',
                'db_table': 'registro_eventos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='registro_ev_fecha_h_5909a2_idx'), models.Index(fields=['usuario_ejecutor', '-fecha_hora'], name='registro_ev_usuario_d72050_idx')],
            },
        ),
    ]
