# Generated by Django 5.2.7 on 2025-11-05 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('personal', '0011_alter_personal_cargo_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroevento',
            name='personal_afectado',
            field=models.ForeignKey(blank=True, help_text='Personal sobre el que se realizó la acción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_personal', to='personal.personal'),
        ),
        migrations.AddIndex(
            model_name='registroevento',
            index=models.Index(fields=['personal_afectado', '-fecha_hora'], name='registro_ev_persona_c0f47f_idx'),
        ),
    ]
