# Generated by Django 5.2.7 on 2025-10-07 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CondicionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('NOMBRADO', 'Nombrado'), ('CONTRATADO', 'Contratado'), ('CAS', 'CAS'), ('DESTACADO', 'Destacado'), ('COMISIONADO', 'Comisionado')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Condición Laboral',
                'verbose_name_plural': 'Condiciones Laborales',
                'db_table': 'condiciones_laborales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('DL276', 'Decreto Legislativo 276'), ('DL728', 'Decreto Legislativo 728'), ('CAS', 'Contrato Administrativo de Servicios'), ('LOCACION', 'Locación de Servicios'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Régimen',
                'verbose_name_plural': 'Regímenes',
                'db_table': 'regimenes',
                'ordering': ['nombre'],
            },
        ),
    ]
