# Generated by Django 5.2.7 on 2025-10-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicionlaboral',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='regimen',
            name='tipo',
        ),
    ]
