# Generated by Django 5.2.7 on 2025-10-27 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número del tipo (1-9)', unique=True)),
                ('nombre', models.CharField(help_text='Nombre del tipo de documento', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de documento', null=True)),
                ('color', models.CharField(default='#e0e0e0', help_text='Color para la UI (hexadecimal)', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el tipo está activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipos_documento',
                'ordering': ['numero'],
            },
        ),
    ]
