# Generated by Django 5.2.7 on 2025-10-30 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionLegajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de la sección (1-9)', unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la sección', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la sección', null=True)),
                ('color', models.CharField(default='#1976d2', help_text='Color para la UI (hexadecimal)', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la sección está activa')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección de Legajo',
                'verbose_name_plural': 'Secciones de Legajo',
                'db_table': 'secciones_legajo',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['seccion__numero', 'numero'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='codigo',
            field=models.CharField(default='TEMP', help_text="Código único del tipo (ej: '1.1', '2.3', '4.15')", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='es_obligatorio',
            field=models.BooleanField(default=False, help_text='Indica si es un documento obligatorio'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de visualización dentro de la sección'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(help_text='Nombre del tipo de documento', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='numero',
            field=models.IntegerField(help_text='Número del subtipo dentro de la sección (ej: 1, 2, 3 para 1.1, 1.2, 1.3)'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='seccion',
            field=models.ForeignKey(default=1, help_text='Sección a la que pertenece este tipo', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='organizacion.seccionlegajo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tipodocumento',
            unique_together={('seccion', 'numero')},
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='color',
        ),
    ]
