# Generated by Django 5.2.7 on 2025-10-30 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_seccionlegajo_alter_tipodocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AlterUniqueTogether(
            name='tipodocumento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no aparecerá en los selectores'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código opcional para identificar el tipo (ej: MEM, SOL, OF)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del tipo de documento', null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='es_obligatorio',
            field=models.BooleanField(default=False, help_text='Indica si este tipo de documento es obligatorio en el legajo'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización del registro'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(help_text='Nombre del tipo de documento (ej: Memorándum, Solicitud, Oficio)', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de visualización en los selectores (menor número = primero)'),
        ),
        migrations.AddIndex(
            model_name='tipodocumento',
            index=models.Index(fields=['activo'], name='tipos_docum_activo_ff202f_idx'),
        ),
        migrations.AddIndex(
            model_name='tipodocumento',
            index=models.Index(fields=['nombre'], name='tipos_docum_nombre_a0ef88_idx'),
        ),
        migrations.AddIndex(
            model_name='tipodocumento',
            index=models.Index(fields=['orden'], name='tipos_docum_orden_48e58b_idx'),
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='seccion',
        ),
    ]
