# Generated by Django 5.2.7 on 2025-10-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_alter_tipodocumento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='es_obligatorio',
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(help_text='Nombre del tipo de documento (ej: Memorándum, Solicitud, Oficio)', max_length=200, unique=True),
        ),
    ]
