# Generated by Django 5.2.7 on 2025-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0007_remove_tipodocumento_es_obligatorio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccionlegajo',
            options={'ordering': ['orden'], 'verbose_name': 'Sección de Legajo', 'verbose_name_plural': 'Secciones de Legajo'},
        ),
        migrations.RemoveField(
            model_name='seccionlegajo',
            name='numero',
        ),
        migrations.AlterField(
            model_name='seccionlegajo',
            name='orden',
            field=models.IntegerField(help_text='Orden de visualización (debe ser único)', unique=True),
        ),
    ]
