# Generated by Django 5.2.7 on 2025-11-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0008_alter_seccionlegajo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.RemoveIndex(
            model_name='tipodocumento',
            name='tipos_docum_orden_48e58b_idx',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='orden',
        ),
    ]
