# Generated by Django 5.2.7 on 2025-10-07 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('AGREGAR_DOCUMENTO', 'Agregar Documento al Legajo'), ('SOLICITUD_LEGAJO', 'Solicitud de Legajo'), ('MODIFICACION', 'Modificación de Datos'), ('ACTA', 'Registro de Acta'), ('MEMORANDO', 'Registro de Memorando'), ('OTRO', 'Otro')], max_length=30)),
                ('asunto', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tickets/comentarios/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Comentario de Ticket',
                'verbose_name_plural': 'Comentarios de Tickets',
                'db_table': 'ticket_comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Historial de Ticket',
                'verbose_name_plural': 'Historial de Tickets',
                'db_table': 'ticket_historial',
                'ordering': ['fecha'],
            },
        ),
    ]
