# Generated by Django 5.2.7 on 2025-10-15 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_remove_condicionlaboral_tipo_remove_regimen_tipo'),
        ('tickets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickethistorial',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='tickethistorial',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resuelto_por',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='apellido',
            field=models.CharField(default='Sin datos', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='organizacion.area'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombre',
            field=models.CharField(default='Sin datos', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='persona_responsable',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='TicketComentario',
        ),
        migrations.DeleteModel(
            name='TicketHistorial',
        ),
    ]
