# Generated by Django 5.2.7 on 2025-10-07 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('TITULO', 'Título Profesional'), ('CV', 'Curriculum Vitae'), ('CONTRATO', 'Contrato'), ('RESOLUCION', 'Resolución'), ('CERTIFICADO', 'Certificado'), ('DECLARACION', 'Declaración Jurada'), ('MEMORANDO', 'Memorando'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_documento', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='legajos/')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Documento de Legajo',
                'verbose_name_plural': 'Documentos de Legajo',
                'db_table': 'legajos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cargo_actual', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_personal/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Escalafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_resolucion', models.FileField(blank=True, null=True, upload_to='resoluciones/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.area')),
                ('condicion_laboral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.condicionlaboral')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.regimen')),
            ],
            options={
                'verbose_name': 'Escalafón',
                'verbose_name_plural': 'Escalafones',
                'db_table': 'escalafones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
