# Generated by Django 5.2.7 on 2025-10-07 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legajo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personal',
            name='area_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_actual', to='organizacion.area'),
        ),
        migrations.AddField(
            model_name='personal',
            name='condicion_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_actual', to='organizacion.condicionlaboral'),
        ),
        migrations.AddField(
            model_name='personal',
            name='regimen_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_actual', to='organizacion.regimen'),
        ),
        migrations.AddField(
            model_name='legajo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legajos', to='personal.personal'),
        ),
        migrations.AddField(
            model_name='escalafon',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalafones', to='personal.personal'),
        ),
    ]
