# Generated by Django 5.2.7 on 2025-10-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='foto',
        ),
        migrations.AddField(
            model_name='personal',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_personal/'),
        ),
    ]
