# Generated by Django 5.2.7 on 2025-10-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_tipodocumento'),
        ('personal', '0003_remove_personal_foto_personal_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajo',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento según los 9 tipos del SIGELP', on_delete=django.db.models.deletion.PROTECT, to='organizacion.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='documento',
            field=models.FileField(default=9, upload_to='documentos_personal/'),
            preserve_default=False,
        ),
    ]
