# Generated by Django 5.2.7 on 2025-10-28 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_tipodocumento'),
        ('personal', '0004_alter_legajo_tipo_documento_alter_personal_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legajo',
            options={'ordering': ['-fecha_documento'], 'verbose_name': 'Documento de Legajo', 'verbose_name_plural': 'Documentos de Legajo'},
        ),
        migrations.RenameField(
            model_name='legajo',
            old_name='fecha_registro',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='legajo',
            name='nombre_documento',
        ),
        migrations.RemoveField(
            model_name='legajo',
            name='numero_documento',
        ),
        migrations.AddField(
            model_name='legajo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='archivo',
            field=models.FileField(help_text='Archivo PDF del documento', upload_to='legajos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del documento', null=True),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='fecha_documento',
            field=models.DateTimeField(auto_now_add=True, default=9, help_text='Fecha y hora de registro del documento (timestamp automático)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legajo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legajos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento según los 9 tipos del SIGELP', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='organizacion.tipodocumento'),
        ),
    ]
