# Generated by Django 5.2.7 on 2025-10-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_legajo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legajo',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Documento de Legajo', 'verbose_name_plural': 'Documentos de Legajo'},
        ),
        migrations.RenameField(
            model_name='legajo',
            old_name='fecha_documento',
            new_name='fecha_registro',
        ),
    ]
