# Generated by Django 5.2.7 on 2025-10-28 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_tipodocumento'),
        ('personal', '0006_alter_legajo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='legajo',
            index=models.Index(fields=['-fecha_registro'], name='legajos_fecha_r_62d3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='legajo',
            index=models.Index(fields=['registrado_por', '-fecha_registro'], name='legajos_registr_b140c4_idx'),
        ),
    ]
