# Generated by Django 5.2.7 on 2025-10-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_legajo_legajos_fecha_r_62d3f3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='legajo',
            name='legajos_fecha_r_62d3f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='legajo',
            name='legajos_registr_b140c4_idx',
        ),
    ]
