# Generated by Django 5.2.7 on 2025-11-05 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0009_alter_tipodocumento_options_and_more'),
        ('personal', '0008_remove_legajo_legajos_fecha_r_62d3f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legajo',
            name='seccion',
            field=models.ForeignKey(default=1, help_text='Sección del legajo donde se guarda (1-9 según SIGELP)', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='organizacion.seccionlegajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legajo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del documento en el sistema (automático)'),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='personal',
            field=models.ForeignKey(help_text='Personal al que pertenece el documento', on_delete=django.db.models.deletion.CASCADE, related_name='legajos', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='registrado_por',
            field=models.ForeignKey(help_text='Usuario que agregó el documento al sistema', on_delete=django.db.models.deletion.PROTECT, related_name='legajos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento (ej: DNI, Memorándum, Solicitud, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='organizacion.tipodocumento'),
        ),
        migrations.AddIndex(
            model_name='legajo',
            index=models.Index(fields=['personal', 'seccion'], name='legajos_persona_2aac2b_idx'),
        ),
        migrations.AddIndex(
            model_name='legajo',
            index=models.Index(fields=['personal', 'tipo_documento'], name='legajos_persona_0181de_idx'),
        ),
        migrations.AddIndex(
            model_name='legajo',
            index=models.Index(fields=['seccion'], name='legajos_seccion_0aa6ad_idx'),
        ),
    ]
