# Generated by Django 5.2.7 on 2025-11-05 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0009_alter_tipodocumento_options_and_more'),
        ('personal', '0009_legajo_seccion_alter_legajo_fecha_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legajo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Documento de Legajo', 'verbose_name_plural': 'Documentos de Legajo'},
        ),
        migrations.RemoveField(
            model_name='legajo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='legajo',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='legajo',
            name='archivo',
            field=models.FileField(help_text='Archivo PDF del documento', max_length=500, upload_to='legajos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se subió el documento (automático)'),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='registrado_por',
            field=models.ForeignKey(help_text='Usuario que subió el documento', on_delete=django.db.models.deletion.PROTECT, related_name='legajos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='seccion',
            field=models.ForeignKey(help_text='Sección del legajo (1-9 según SIGELP)', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='organizacion.seccionlegajo'),
        ),
        migrations.AlterField(
            model_name='legajo',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='organizacion.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cargo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_actual', to='organizacion.cargo'),
        ),
        migrations.AddIndex(
            model_name='legajo',
            index=models.Index(fields=['-fecha_creacion'], name='legajos_fecha_c_3c5e14_idx'),
        ),
    ]
