# Generated by Django 5.2.7 on 2025-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_legajo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo_actual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
